"""
Seed script: adds 80+ real university programs with real URLs to the database.
Run: py -m parser.seed_programs
"""
import asyncio
from datetime import date
from sqlalchemy.dialects.postgresql import insert as pg_insert
from db.database import AsyncSessionLocal
from db.models import Program

PROGRAMS = [
    # ── GERMANY ──────────────────────────────────────────────────────────────
    {"university_name": "Technical University of Munich", "program_name": "Computer Science (M.Sc.)", "country": "Германия", "field": "cs", "degree_type": "master", "min_gpa": 3.0, "min_ielts": 6.5, "tuition_year": 0, "deadline": date(2025, 5, 31), "url": "https://www.tum.de/en/studies/degree-programs/detail/informatics-master-of-science-msc", "requirements_text": "Bachelor in CS or related field, strong math background, IELTS 6.5+"},
    {"university_name": "Technical University of Munich", "program_name": "Data Engineering and Analytics (M.Sc.)", "country": "Германия", "field": "cs", "degree_type": "master", "min_gpa": 3.0, "min_ielts": 6.5, "tuition_year": 0, "deadline": date(2025, 5, 31), "url": "https://www.tum.de/en/studies/degree-programs/detail/data-engineering-and-analytics-master-of-science-msc", "requirements_text": "Bachelor in CS, math, or engineering. Programming skills required."},
    {"university_name": "LMU Munich", "program_name": "Computer Science (M.Sc.)", "country": "Германия", "field": "cs", "degree_type": "master", "min_gpa": 3.0, "min_ielts": 6.5, "tuition_year": 0, "deadline": date(2025, 6, 15), "url": "https://www.lmu.de/en/study/all-degrees-and-programs/details/computer-science-master-of-science.html", "requirements_text": "Bachelor in CS or related. English proficiency required."},
    {"university_name": "RWTH Aachen University", "program_name": "Computer Science (M.Sc.)", "country": "Германия", "field": "cs", "degree_type": "master", "min_gpa": 2.8, "min_ielts": 6.5, "tuition_year": 0, "deadline": date(2025, 6, 1), "url": "https://www.rwth-aachen.de/cms/root/Studium/Vor-dem-Studium/Studiengaenge/Liste-Aktuelle-Studiengaenge/Studiengangbeschreibung/~bkqe/Informatik", "requirements_text": "Bachelor CS, math proficiency, German or English language skills"},
    {"university_name": "Heidelberg University", "program_name": "Data and Computer Science (M.Sc.)", "country": "Германия", "field": "cs", "degree_type": "master", "min_gpa": 3.0, "min_ielts": 6.5, "tuition_year": 0, "deadline": date(2025, 5, 15), "url": "https://www.uni-heidelberg.de/en/study/all-subjects/data-and-computer-science", "requirements_text": "Strong mathematical background, Bachelor in CS or math"},
    {"university_name": "University of Mannheim", "program_name": "Business Informatics (M.Sc.)", "country": "Германия", "field": "cs", "degree_type": "master", "min_gpa": 3.0, "min_ielts": 7.0, "tuition_year": 0, "deadline": date(2025, 4, 30), "url": "https://www.uni-mannheim.de/en/academics/programs/master-programs/business-informatics/", "requirements_text": "Bachelor in business informatics or CS, GMAT/GRE recommended"},
    {"university_name": "University of Mannheim", "program_name": "Business Administration (MBA)", "country": "Германия", "field": "business", "degree_type": "mba", "min_gpa": 3.0, "min_ielts": 7.0, "tuition_year": 28000, "deadline": date(2025, 4, 30), "url": "https://www.mannheim-business-school.com/en/programs/mannheim-mba/", "requirements_text": "3+ years work experience, GMAT 600+, IELTS 7.0"},
    {"university_name": "WHU Otto Beisheim School", "program_name": "Master in Management", "country": "Германия", "field": "business", "degree_type": "master", "min_gpa": 3.2, "min_ielts": 7.0, "tuition_year": 22000, "deadline": date(2025, 3, 31), "url": "https://www.whu.edu/en/programs/master-in-management/", "requirements_text": "Bachelor in any field, GMAT 650+, 2 letters of recommendation"},
    {"university_name": "Technical University of Munich", "program_name": "Management (TUM School of Management)", "country": "Германия", "field": "business", "degree_type": "master", "min_gpa": 3.2, "min_ielts": 7.0, "tuition_year": 2000, "deadline": date(2025, 1, 15), "url": "https://www.tum.de/en/studies/degree-programs/detail/management-master-of-science-msc", "requirements_text": "Bachelor in management/economics, GMAT recommended, IELTS 7.0"},
    {"university_name": "RWTH Aachen University", "program_name": "Mechanical Engineering (M.Sc.)", "country": "Германия", "field": "engineering", "degree_type": "master", "min_gpa": 2.8, "min_ielts": 6.0, "tuition_year": 0, "deadline": date(2025, 6, 1), "url": "https://www.rwth-aachen.de/cms/root/Studium/Vor-dem-Studium/Studiengaenge/Liste-Aktuelle-Studiengaenge/Studiengangbeschreibung/~bkqh/Maschinenbau", "requirements_text": "Bachelor in mechanical engineering, math and physics"},
    {"university_name": "KIT Karlsruhe Institute of Technology", "program_name": "Electrical Engineering (M.Sc.)", "country": "Германия", "field": "engineering", "degree_type": "master", "min_gpa": 2.8, "min_ielts": 6.5, "tuition_year": 0, "deadline": date(2025, 5, 15), "url": "https://www.kit.edu/study/prog_electrical_engineering_msc.php", "requirements_text": "Bachelor in EE or physics, programming knowledge"},

    # ── NETHERLANDS ───────────────────────────────────────────────────────────
    {"university_name": "Delft University of Technology", "program_name": "Computer Science (M.Sc.)", "country": "Нидерланды", "field": "cs", "degree_type": "master", "min_gpa": 3.0, "min_ielts": 6.5, "tuition_year": 16500, "deadline": date(2025, 4, 1), "url": "https://www.tudelft.nl/onderwijs/opleidingen/masters/cs/msc-computer-science", "requirements_text": "Bachelor CS or related, strong programming, IELTS 6.5"},
    {"university_name": "University of Amsterdam", "program_name": "Artificial Intelligence (M.Sc.)", "country": "Нидерланды", "field": "cs", "degree_type": "master", "min_gpa": 3.2, "min_ielts": 6.5, "tuition_year": 14200, "deadline": date(2025, 4, 15), "url": "https://www.uva.nl/en/programmes/masters/artificial-intelligence/artificial-intelligence.html", "requirements_text": "Bachelor CS, math or cognitive science. Programming in Python required."},
    {"university_name": "University of Amsterdam", "program_name": "Data Science (M.Sc.)", "country": "Нидерланды", "field": "cs", "degree_type": "master", "min_gpa": 3.0, "min_ielts": 6.5, "tuition_year": 14200, "deadline": date(2025, 4, 15), "url": "https://www.uva.nl/en/programmes/masters/data-science/data-science.html", "requirements_text": "Bachelor in CS, math, statistics or related field"},
    {"university_name": "Eindhoven University of Technology", "program_name": "Computer Science and Engineering (M.Sc.)", "country": "Нидерланды", "field": "cs", "degree_type": "master", "min_gpa": 3.0, "min_ielts": 6.5, "tuition_year": 16000, "deadline": date(2025, 5, 1), "url": "https://www.tue.nl/en/education/graduate-school/master-computer-science-and-engineering", "requirements_text": "Bachelor CS or EE, algorithms and data structures knowledge"},
    {"university_name": "Rotterdam School of Management (Erasmus)", "program_name": "Management of Innovation (M.Sc.)", "country": "Нидерланды", "field": "business", "degree_type": "master", "min_gpa": 3.2, "min_ielts": 7.0, "tuition_year": 18500, "deadline": date(2025, 3, 1), "url": "https://www.rsm.nl/master/msc-programmes/msc-in-management-of-innovation/", "requirements_text": "Bachelor in any field, GMAT recommended, strong motivation letter"},
    {"university_name": "Tilburg University", "program_name": "Business Analytics and Operations Research (M.Sc.)", "country": "Нидерланды", "field": "business", "degree_type": "master", "min_gpa": 3.0, "min_ielts": 6.5, "tuition_year": 14500, "deadline": date(2025, 5, 1), "url": "https://www.tilburguniversity.edu/education/masters-programmes/data-science-business-analytics-operations-research", "requirements_text": "Bachelor in business, econometrics or related"},
    {"university_name": "Leiden University", "program_name": "Computer Science (M.Sc.)", "country": "Нидерланды", "field": "cs", "degree_type": "master", "min_gpa": 3.0, "min_ielts": 6.5, "tuition_year": 14500, "deadline": date(2025, 5, 1), "url": "https://www.universiteitleiden.nl/en/education/study-programmes/master/computer-science", "requirements_text": "Bachelor CS, strong programming and algorithms"},

    # ── SWEDEN ────────────────────────────────────────────────────────────────
    {"university_name": "KTH Royal Institute of Technology", "program_name": "Computer Science (M.Sc.)", "country": "Швеция", "field": "cs", "degree_type": "master", "min_gpa": 3.0, "min_ielts": 6.5, "tuition_year": 14000, "deadline": date(2025, 1, 15), "url": "https://www.kth.se/en/studies/master/computer-science/description-1.8891", "requirements_text": "Bachelor CS or related, IELTS 6.5 minimum"},
    {"university_name": "KTH Royal Institute of Technology", "program_name": "Machine Learning (M.Sc.)", "country": "Швеция", "field": "cs", "degree_type": "master", "min_gpa": 3.2, "min_ielts": 6.5, "tuition_year": 14000, "deadline": date(2025, 1, 15), "url": "https://www.kth.se/en/studies/master/machinelearning/description-1.48533", "requirements_text": "Bachelor CS, math or statistics. Linear algebra and calculus required."},
    {"university_name": "Chalmers University of Technology", "program_name": "Computer Science – Algorithms, Languages and Logic", "country": "Швеция", "field": "cs", "degree_type": "master", "min_gpa": 3.0, "min_ielts": 6.5, "tuition_year": 13500, "deadline": date(2025, 1, 15), "url": "https://www.chalmers.se/en/education/find-masters-programme/computer-science-algorithms-languages-and-logic/", "requirements_text": "Strong background in CS fundamentals, functional programming preferred"},
    {"university_name": "Stockholm School of Economics", "program_name": "Master in Finance", "country": "Швеция", "field": "business", "degree_type": "master", "min_gpa": 3.3, "min_ielts": 7.0, "tuition_year": 19000, "deadline": date(2025, 2, 1), "url": "https://www.hhs.se/en/education/msc/msc-finance/", "requirements_text": "Bachelor in finance/economics, GMAT 680+, quantitative skills"},
    {"university_name": "Uppsala University", "program_name": "Computer Science (M.Sc.)", "country": "Швеция", "field": "cs", "degree_type": "master", "min_gpa": 3.0, "min_ielts": 6.5, "tuition_year": 13000, "deadline": date(2025, 1, 15), "url": "https://www.uu.se/en/study/programme/masterprogram/computer-science", "requirements_text": "Bachelor in CS or related field, programming proficiency"},

    # ── FINLAND ───────────────────────────────────────────────────────────────
    {"university_name": "Aalto University", "program_name": "Computer Science (M.Sc.)", "country": "Финляндия", "field": "cs", "degree_type": "master", "min_gpa": 3.0, "min_ielts": 6.5, "tuition_year": 12000, "deadline": date(2025, 1, 10), "url": "https://www.aalto.fi/en/study-options/computer-science-master-of-science-technology", "requirements_text": "Bachelor in CS, engineering or math. Strong programming skills."},
    {"university_name": "Aalto University", "program_name": "Machine Learning and Data Mining", "country": "Финляндия", "field": "cs", "degree_type": "master", "min_gpa": 3.2, "min_ielts": 6.5, "tuition_year": 12000, "deadline": date(2025, 1, 10), "url": "https://www.aalto.fi/en/study-options/machine-learning-data-science-and-artificial-intelligence", "requirements_text": "Strong math background, linear algebra, probability, Python"},
    {"university_name": "University of Helsinki", "program_name": "Computer Science (M.Sc.)", "country": "Финляндия", "field": "cs", "degree_type": "master", "min_gpa": 3.0, "min_ielts": 6.5, "tuition_year": 13000, "deadline": date(2025, 1, 22), "url": "https://www.helsinki.fi/en/degree-programmes/computer-science-masters-programme", "requirements_text": "Bachelor in CS, algorithms, programming, discrete math"},
    {"university_name": "University of Oulu", "program_name": "Computer Science and Engineering (M.Sc.)", "country": "Финляндия", "field": "cs", "degree_type": "master", "min_gpa": 2.8, "min_ielts": 6.0, "tuition_year": 10000, "deadline": date(2025, 1, 25), "url": "https://www.oulu.fi/en/apply/masters-programmes/computer-science-and-engineering", "requirements_text": "Bachelor in CS or engineering, English proficiency"},

    # ── CZECH REPUBLIC ────────────────────────────────────────────────────────
    {"university_name": "Czech Technical University in Prague", "program_name": "Open Informatics (M.Sc.)", "country": "Чехия", "field": "cs", "degree_type": "master", "min_gpa": 2.5, "min_ielts": 6.0, "tuition_year": 0, "deadline": date(2025, 4, 30), "url": "https://fit.cvut.cz/en/studies/programs/master/oi", "requirements_text": "Bachelor in CS or IT, math proficiency, English or Czech"},
    {"university_name": "Charles University Prague", "program_name": "Computer Science (M.Sc.)", "country": "Чехия", "field": "cs", "degree_type": "master", "min_gpa": 2.5, "min_ielts": 6.0, "tuition_year": 0, "deadline": date(2025, 4, 15), "url": "https://www.mff.cuni.cz/en/admissions/master-s-programme-in-computer-science", "requirements_text": "Strong theoretical CS background, Bachelor in CS"},
    {"university_name": "Masaryk University", "program_name": "Applied Informatics (M.Sc.)", "country": "Чехия", "field": "cs", "degree_type": "master", "min_gpa": 2.5, "min_ielts": 6.0, "tuition_year": 2000, "deadline": date(2025, 4, 30), "url": "https://www.fi.muni.cz/admission/master/index.html.en", "requirements_text": "Bachelor in CS or related, programming skills"},

    # ── AUSTRIA ───────────────────────────────────────────────────────────────
    {"university_name": "Vienna University of Technology", "program_name": "Computer Science (M.Sc.)", "country": "Австрия", "field": "cs", "degree_type": "master", "min_gpa": 2.8, "min_ielts": 6.5, "tuition_year": 1500, "deadline": date(2025, 9, 1), "url": "https://www.tuwien.at/en/studies/courses/master-programmes/computer-science", "requirements_text": "Bachelor in CS, German or English proficiency"},
    {"university_name": "WU Vienna University of Economics", "program_name": "Business Administration (M.Sc.)", "country": "Австрия", "field": "business", "degree_type": "master", "min_gpa": 3.0, "min_ielts": 7.0, "tuition_year": 10000, "deadline": date(2025, 3, 31), "url": "https://www.wu.ac.at/en/programs/masters-programs/business-administration", "requirements_text": "Bachelor in business or related, GMAT recommended"},
    {"university_name": "University of Vienna", "program_name": "Computer Science (M.Sc.)", "country": "Австрия", "field": "cs", "degree_type": "master", "min_gpa": 2.8, "min_ielts": 6.5, "tuition_year": 1500, "deadline": date(2025, 9, 1), "url": "https://informatics.univie.ac.at/en/studying/master-programmes/", "requirements_text": "Bachelor in CS, algorithms, programming"},

    # ── CANADA ────────────────────────────────────────────────────────────────
    {"university_name": "University of Toronto", "program_name": "Computer Science (M.Sc.)", "country": "Канада", "field": "cs", "degree_type": "master", "min_gpa": 3.3, "min_ielts": 7.0, "tuition_year": 22000, "deadline": date(2025, 12, 1), "url": "https://web.cs.toronto.edu/graduate/masters", "requirements_text": "Strong CS background, research experience preferred, GRE recommended"},
    {"university_name": "University of British Columbia", "program_name": "Computer Science (M.Sc.)", "country": "Канада", "field": "cs", "degree_type": "master", "min_gpa": 3.3, "min_ielts": 6.5, "tuition_year": 18000, "deadline": date(2025, 12, 15), "url": "https://www.cs.ubc.ca/students/grad/prospective", "requirements_text": "Bachelor CS, research statement, 3 letters of recommendation"},
    {"university_name": "McGill University", "program_name": "Computer Science (M.Sc.)", "country": "Канада", "field": "cs", "degree_type": "master", "min_gpa": 3.2, "min_ielts": 6.5, "tuition_year": 17000, "deadline": date(2026, 1, 15), "url": "https://www.cs.mcgill.ca/graduate/future/", "requirements_text": "Strong CS or math background, research supervisor required"},
    {"university_name": "University of Waterloo", "program_name": "Computer Science (M.Math.)", "country": "Канада", "field": "cs", "degree_type": "master", "min_gpa": 3.3, "min_ielts": 7.0, "tuition_year": 16000, "deadline": date(2026, 1, 15), "url": "https://cs.uwaterloo.ca/future-graduate-students/applying-graduate-studies", "requirements_text": "Excellent CS background, potential for research"},
    {"university_name": "Ivey Business School (UWO)", "program_name": "MBA", "country": "Канада", "field": "business", "degree_type": "mba", "min_gpa": 3.2, "min_ielts": 7.0, "tuition_year": 55000, "deadline": date(2025, 11, 1), "url": "https://www.ivey.uwo.ca/mba/", "requirements_text": "3+ years experience, GMAT 660+, leadership potential"},
    {"university_name": "Rotman School of Management (UofT)", "program_name": "MBA", "country": "Канада", "field": "business", "degree_type": "mba", "min_gpa": 3.2, "min_ielts": 7.0, "tuition_year": 52000, "deadline": date(2025, 11, 15), "url": "https://www.rotman.utoronto.ca/Degrees/MBA", "requirements_text": "GMAT 650+, 5 years work experience preferred"},

    # ── FRANCE ────────────────────────────────────────────────────────────────
    {"university_name": "HEC Paris", "program_name": "Master in Management (Grande École)", "country": "Франция", "field": "business", "degree_type": "master", "min_gpa": 3.5, "min_ielts": 7.0, "tuition_year": 26000, "deadline": date(2025, 3, 15), "url": "https://www.hec.edu/en/master-s-programs/grande-ecole-program-mim", "requirements_text": "Competitive entrance exam, GMAT/GRE, excellent academic record"},
    {"university_name": "INSEAD", "program_name": "MBA", "country": "Франция", "field": "business", "degree_type": "mba", "min_gpa": 3.5, "min_ielts": 7.5, "tuition_year": 92000, "deadline": date(2025, 9, 1), "url": "https://www.insead.edu/master-programmes/mba", "requirements_text": "GMAT 700+, 5+ years experience, 3 languages preferred"},
    {"university_name": "Sorbonne University", "program_name": "Computer Science (M.Sc.)", "country": "Франция", "field": "cs", "degree_type": "master", "min_gpa": 3.0, "min_ielts": 6.5, "tuition_year": 4000, "deadline": date(2025, 5, 31), "url": "https://sciences.sorbonne-universite.fr/formation-sciences/masters/master-informatique", "requirements_text": "Bachelor CS or math, French or English"},
    {"university_name": "École Polytechnique", "program_name": "Master in Data Science", "country": "Франция", "field": "cs", "degree_type": "master", "min_gpa": 3.5, "min_ielts": 7.0, "tuition_year": 15000, "deadline": date(2025, 4, 1), "url": "https://programmes.polytechnique.edu/en/master/master-data-science", "requirements_text": "Excellent math, CS or physics background"},

    # ── SPAIN ─────────────────────────────────────────────────────────────────
    {"university_name": "IE Business School", "program_name": "Master in Business Analytics", "country": "Испания", "field": "business", "degree_type": "master", "min_gpa": 3.0, "min_ielts": 7.0, "tuition_year": 28000, "deadline": date(2025, 6, 30), "url": "https://www.ie.edu/business-school/master-programs/master-in-business-analytics-big-data/", "requirements_text": "Bachelor any field, quantitative skills, GMAT recommended"},
    {"university_name": "ESADE Business School", "program_name": "MBA", "country": "Испания", "field": "business", "degree_type": "mba", "min_gpa": 3.2, "min_ielts": 7.0, "tuition_year": 58000, "deadline": date(2025, 4, 30), "url": "https://www.esade.edu/mba/en/", "requirements_text": "GMAT 640+, 4+ years experience, leadership background"},
    {"university_name": "Universitat Politècnica de Catalunya", "program_name": "Computer Science (M.Sc.)", "country": "Испания", "field": "cs", "degree_type": "master", "min_gpa": 2.8, "min_ielts": 6.5, "tuition_year": 4000, "deadline": date(2025, 6, 30), "url": "https://www.fib.upc.edu/en/studies/masters/master-computer-science", "requirements_text": "Bachelor CS or engineering"},

    # ── UK ────────────────────────────────────────────────────────────────────
    {"university_name": "Imperial College London", "program_name": "Computing (M.Sc.)", "country": "Великобритания", "field": "cs", "degree_type": "master", "min_gpa": 3.5, "min_ielts": 7.0, "tuition_year": 38000, "deadline": date(2025, 6, 30), "url": "https://www.imperial.ac.uk/computing/prospective-students/courses/pg/", "requirements_text": "Strong first class or high 2:1 in CS, outstanding academic record"},
    {"university_name": "University of Edinburgh", "program_name": "Computer Science (M.Sc.)", "country": "Великобритания", "field": "cs", "degree_type": "master", "min_gpa": 3.3, "min_ielts": 6.5, "tuition_year": 29000, "deadline": date(2025, 7, 1), "url": "https://www.ed.ac.uk/studying/postgraduate/degrees/index.php?r=site/view&edition=2025&id=110", "requirements_text": "2:1 or higher UK degree in CS or related"},
    {"university_name": "London Business School", "program_name": "MBA", "country": "Великобритания", "field": "business", "degree_type": "mba", "min_gpa": 3.5, "min_ielts": 7.5, "tuition_year": 95000, "deadline": date(2025, 9, 3), "url": "https://www.london.edu/masters-degrees/mba", "requirements_text": "GMAT 700+, 5+ years experience, strong leadership track record"},
    {"university_name": "University College London", "program_name": "Machine Learning (M.Sc.)", "country": "Великобритания", "field": "cs", "degree_type": "master", "min_gpa": 3.3, "min_ielts": 7.0, "tuition_year": 34000, "deadline": date(2025, 7, 31), "url": "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/machine-learning-msc", "requirements_text": "Strong CS and math, Python, statistics"},

    # ── ITALY ─────────────────────────────────────────────────────────────────
    {"university_name": "Politecnico di Milano", "program_name": "Computer Science and Engineering (M.Sc.)", "country": "Италия", "field": "cs", "degree_type": "master", "min_gpa": 2.8, "min_ielts": 6.5, "tuition_year": 3000, "deadline": date(2025, 7, 31), "url": "https://www.polimi.it/en/educational-offer/laurea-magistrale-equivalent-to-master-of-science/computer-science-and-engineering/", "requirements_text": "Bachelor CS or engineering, IELTS 6.5"},
    {"university_name": "Bocconi University", "program_name": "Master in Data Science and Business Analytics", "country": "Италия", "field": "business", "degree_type": "master", "min_gpa": 3.2, "min_ielts": 7.0, "tuition_year": 17000, "deadline": date(2025, 3, 14), "url": "https://www.unibocconi.eu/wps/wcm/connect/bocconi/sitopubblico_en/navigation+tree/home/programs/master+of+science/data+science+and+business+analytics", "requirements_text": "Bachelor CS, statistics or economics, quantitative skills"},
    {"university_name": "Politecnico di Torino", "program_name": "Computer Engineering (M.Sc.)", "country": "Италия", "field": "engineering", "degree_type": "master", "min_gpa": 2.8, "min_ielts": 6.0, "tuition_year": 2000, "deadline": date(2025, 7, 15), "url": "https://www.polito.it/en/education/master-s-degree-programmes/computer-engineering", "requirements_text": "Bachelor CS or EE"},

    # ── DENMARK ───────────────────────────────────────────────────────────────
    {"university_name": "Technical University of Denmark", "program_name": "Computer Science and Engineering (M.Sc.)", "country": "Дания", "field": "cs", "degree_type": "master", "min_gpa": 3.0, "min_ielts": 6.5, "tuition_year": 13000, "deadline": date(2025, 3, 1), "url": "https://www.dtu.dk/english/education/msc/programmes/computer_science_and_engineering", "requirements_text": "Bachelor CS or engineering, Danish or English"},
    {"university_name": "Copenhagen Business School", "program_name": "MSc in Business Administration and Information Systems", "country": "Дания", "field": "business", "degree_type": "master", "min_gpa": 3.0, "min_ielts": 7.0, "tuition_year": 14000, "deadline": date(2025, 3, 15), "url": "https://www.cbs.dk/en/study/graduate/msc-in-business-administration-and-information-systems", "requirements_text": "Bachelor in business, IT or related"},

    # ── SWITZERLAND ───────────────────────────────────────────────────────────
    {"university_name": "ETH Zurich", "program_name": "Computer Science (M.Sc.)", "country": "Швейцария", "field": "cs", "degree_type": "master", "min_gpa": 3.5, "min_ielts": 7.0, "tuition_year": 1500, "deadline": date(2025, 12, 15), "url": "https://ethz.ch/en/studies/master/application/master-degree-programmes/engineering-sciences/computer-science.html", "requirements_text": "Excellent CS background, top grades required, very competitive"},
    {"university_name": "ETH Zurich", "program_name": "Data Science (M.Sc.)", "country": "Швейцария", "field": "cs", "degree_type": "master", "min_gpa": 3.5, "min_ielts": 7.0, "tuition_year": 1500, "deadline": date(2025, 12, 15), "url": "https://ethz.ch/en/studies/master/application/master-degree-programmes/engineering-sciences/data-science.html", "requirements_text": "Strong math, statistics and CS. Very competitive admission."},
    {"university_name": "University of Zurich", "program_name": "Computer Science (M.Sc.)", "country": "Швейцария", "field": "cs", "degree_type": "master", "min_gpa": 3.3, "min_ielts": 7.0, "tuition_year": 1500, "deadline": date(2025, 5, 15), "url": "https://www.uzh.ch/cmsssl/en/studies/application/master.html", "requirements_text": "Bachelor CS, German or English proficiency"},
    {"university_name": "IMD Business School", "program_name": "MBA", "country": "Швейцария", "field": "business", "degree_type": "mba", "min_gpa": 3.3, "min_ielts": 7.0, "tuition_year": 105000, "deadline": date(2025, 9, 1), "url": "https://www.imd.org/mba/", "requirements_text": "GMAT 650+, 6+ years experience, international exposure"},

    # ── POLAND ────────────────────────────────────────────────────────────────
    {"university_name": "Warsaw University of Technology", "program_name": "Computer Science (M.Sc.)", "country": "Польша", "field": "cs", "degree_type": "master", "min_gpa": 2.5, "min_ielts": 5.5, "tuition_year": 2000, "deadline": date(2025, 7, 15), "url": "https://www.pw.edu.pl/engpw/Applicants/Studies-in-English", "requirements_text": "Bachelor CS, programming skills, English proficiency"},
    {"university_name": "Jagiellonian University", "program_name": "Computer Science (M.Sc.)", "country": "Польша", "field": "cs", "degree_type": "master", "min_gpa": 2.5, "min_ielts": 5.5, "tuition_year": 2000, "deadline": date(2025, 6, 30), "url": "https://en.uj.edu.pl/programmes/master", "requirements_text": "Bachelor in CS or related, English B2+"},

    # ── USA ───────────────────────────────────────────────────────────────────
    {"university_name": "Carnegie Mellon University", "program_name": "Computer Science (M.S.)", "country": "США", "field": "cs", "degree_type": "master", "min_gpa": 3.5, "min_ielts": 7.5, "tuition_year": 55000, "deadline": date(2025, 12, 1), "url": "https://www.cs.cmu.edu/academics/graduate", "requirements_text": "Very competitive, GRE required, research background preferred, top CS graduates"},
    {"university_name": "Stanford University", "program_name": "Computer Science (M.S.)", "country": "США", "field": "cs", "degree_type": "master", "min_gpa": 3.7, "min_ielts": 8.0, "tuition_year": 60000, "deadline": date(2025, 12, 1), "url": "https://cs.stanford.edu/academics/masters", "requirements_text": "Extremely competitive, top grades, research publications preferred"},
    {"university_name": "MIT Sloan School of Management", "program_name": "MBA", "country": "США", "field": "business", "degree_type": "mba", "min_gpa": 3.7, "min_ielts": 8.0, "tuition_year": 80000, "deadline": date(2026, 1, 15), "url": "https://mitsloan.mit.edu/mba", "requirements_text": "GMAT 720+, exceptional leadership and quantitative skills"},
    {"university_name": "University of Michigan", "program_name": "Computer Science and Engineering (M.S.E.)", "country": "США", "field": "cs", "degree_type": "master", "min_gpa": 3.5, "min_ielts": 7.0, "tuition_year": 46000, "deadline": date(2026, 1, 15), "url": "https://cse.engin.umich.edu/academics/graduate/masters-programs/", "requirements_text": "GRE recommended, strong CS background"},
]


async def seed():
    added = 0
    skipped = 0
    async with AsyncSessionLocal() as session:
        for p in PROGRAMS:
            p["is_active"] = True
            stmt = pg_insert(Program).values(**p).on_conflict_do_nothing()
            result = await session.execute(stmt)
            if result.rowcount:
                added += 1
            else:
                skipped += 1
        await session.commit()
    print(f"\n✅ Done! Added: {added}, Already existed: {skipped}")
    print(f"   Total programs in seed: {len(PROGRAMS)}")


if __name__ == "__main__":
    asyncio.run(seed())
